version: 2
 jobs:
   build:
     working_directory: ~/rugby-ranker
     docker:
       - image: circleci/android:api-28-alpha
     environment:
       JVM_OPTS: -Xmx4g
     steps:
       - checkout
       - restore_cache:
           key: gradle-{{ checksum "build.gradle" }}
       - run:
           name: Download dependencies
           command: ./gradlew androidDependencies
       - save_cache:
           paths:
             - ~/.gradle
           key: gradle-{{ checksum "build.gradle" }}
       - run:
           name: Run ktlint
           command: ./gradlew ktlint
       - store_artifacts:
           path: app/build/reports
           destination: reports
       - run:
           name: Run lint
           command: ./gradlew lintDebug
       - run:
           name: Run unit tests
           command: ./gradlew testDebugUnitTest
       - store_artifacts:
           path: app/build/reports
           destination: reports
       - store_test_results:
           path: app/build/test-results
